### ISSUE TITLE
distribute the release notes

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/release-notes#9]
please @andriineronov @ferrigno
* make sure you can copy the HTML release notes from the github view of the readme (or see the email I sent to contact@odahub.io, if you got it)
* let us know when is it possible to send the email. we can also wait next week I guess, if everybody is there?

**Comment by ferrigno** [comment]
The release note is OK for me. Should I ask to send it through the INTEGRAL newsletter ?

**Comment by volodymyrss** [comment]
I think at this point both you @ferrigno  and @andriineronov  can distribute it at will.
